### ISSUE TITLE
Rancher compatible binary release

### ISSUE THREAD

**Issue by Chris7** [km4rcus/docker-machine-opennebula#1]
Hi,

Sorry in advance that this isn't exactly the correct place to bring this up, but it was the closest I could find.

I noticed you have some overlap with Rancher & ONE. I was wondering if you ever made progress on adding ONE as a new machine host into Rancher? I managed to add the ONE plugin host (by supplying my own built binary), but it fails with the following output:

```
time="2016-09-15T16:57:32Z" level=info msg="Creating Machine" eventId=d4c29984-0004-4d3b-bbdd-af9e4ac25ec3 resourceId=1ph10 
time="2016-09-15T16:57:32Z" level=info msg="Cmd slice: [create -d opennebula --engine-install-url https://releases.rancher.com/install-docker/1.10.sh --opennebula-image-id 1 --opennebula-network-id 0 --opennebula-password username --opennebula-user password --opennebula-xmlrpcurl authurl]" 
time="2016-09-15T16:57:32Z" level=info msg="stdout: Creating CA: /var/lib/cattle/machine/6b5b17ec-ca0f-4dc3-86a2-cb9fc55ce625/certs/ca.pem" resourceId: =1ph10 
time="2016-09-15T16:57:33Z" level=info msg="stdout: Creating client certificate: /var/lib/cattle/machine/6b5b17ec-ca0f-4dc3-86a2-cb9fc55ce625/certs/cert.pem" resourceId: =1ph10 
time="2016-09-15T16:57:33Z" level=info msg="stdout: Running pre-create checks..." resourceId: =1ph10 
time="2016-09-15T16:57:33Z" level=info msg="stdout: Creating machine..." resourceId: =1ph10 
time="2016-09-15T16:57:33Z" level=info msg="stdout: (test-rancher3) Creating SSH key..." resourceId: =1ph10 
time="2016-09-15T16:57:33Z" level=info msg="stdout: (test-rancher3) Starting  VM..." resourceId: =1ph10 
time="2016-09-15T16:57:35Z" level=info msg="stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag." resourceId: =1ph10 
time="2016-09-15T16:57:35Z" level=info msg="stdout: " resourceId: =1ph10 
time="2016-09-15T16:57:36Z" level=info msg="stderr: Error creating machine: Error in driver during machine creation: unexpected EOF" resourceId=1ph10 
time="2016-09-15T16:57:36Z" level=info msg="starting cleanup..." machine name=test-rancher3 
time="2016-09-15T16:57:36Z" level=info msg="cleanup successful" machine name=test-rancher3 
time="2016-09-15T16:57:36Z" level=error msg="Error processing event" err="Error in driver during machine creation: unexpected EOF" eventId=d4c29984-0004-4d3b-bbdd-af9e4ac25ec3 eventName="physicalhost.create;handler=goMachineService" resourceId=1ph10 
```

So now a question -- does this repo address any of these issues? I've been searching around for a prebuilt binary compatible w/ Rancher w/o any luck.

**Comment by km4rcus** [comment]
Hi,

You can use this [image](https://s3-eu-west-1.amazonaws.com/docker-machine-opennebula/docker-machine-driver-opennebula.tgz) I have created for Rancher and it should work with the recent versions.

Let me know if it works.

**Comment by Chris7** [comment]
Thanks for getting back to me. I tried it without any luck -- I'm using Rancher v1.1.3 with OpenNebula v5.0.2. I plan on upgrading Rancher soon and I'll let you know if it works then!

**Comment by km4rcus** [comment]
It seems I can't reproduce the error with Rancher v1.1.3 and OpenNebula v5.0.2. It works for me. Could you tell me which driver options settings and which image (boot2docker,debian,centos,...) you are using?

**Comment by Chris7** [comment]
Hi again,

Just wanted to let you know that my issue was a self signed certificate and this actually works (but just gives a terribly non-informative error). Thank you for your help!
